wandb_version: 1

layer_1:
  desc: null
  value: 512
activation_1:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.30611733005288294
layer_2:
  desc: null
  value: 10
activation_2:
  desc: null
  value: softmax
optimizer:
  desc: null
  value: sgd
loss:
  desc: null
  value: sparse_categorical_crossentropy
metric:
  desc: null
  value: accuracy
epoch:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681481263.127437
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 7
      - 16
      - 23
      - 38
      - 39
      4: 3.8.16
      5: 0.14.2
      8:
      - 1
      - 5
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
